Update to use ArcGIS runtime update 10
Esri/nearby-android pull request #100
Opened 2020-11-30 20:28 UTC by puneet-pdx

- Android Gradle Plugin Version - 4.1.1
- Gradle version - 6.5
- Min SDK - 23 required by ArcGIS runtime
- ArcGIS runtime version - 100.10.0
- googleLocationServicesVersion - 17.1.0
- materialLibraryVersion
- appcompatLibraryVersion

2021-02-19 23:55 UTC, sorenoid approved these changes
👍

2021-02-22 21:34 UTC, esreli requested changes
The changes you've made to the project look good to me, thank you for updating the project and its dependencies accordingly. It appears there doesn't need to be any code changes, nice!

As for the doc, with the launch of the new site there appears to be a number of broken links.

### README

- [License your app](https://github.com/Esri/nearby-android/tree/puneet/updateToUseU10#licensing) leads to `404`. Why don't we point to the android SDK's [License and deployment](https://developers.arcgis.com/android/license-and-deployment/) page?

### docs/README

- [mapless app pattern](https://github.com/Esri/nearby-android/tree/puneet/updateToUseU10/docs#device-location) leads to `404`. I'm not really sure what to link to here, I'm not sure if a mapless pattern is discussed in the new doc. You can probably simply remove this hyperlink, unless you have a good link?

2021-02-23 00:08 UTC, puneet-pdx commented
@esreli I have addressed your comments. Please have another look.

2021-02-23 22:02 UTC, esreli approved these changes
LGTM 👍

2021-02-23 22:02 UTC, esreli commented on README.md
> +For information about licensing your deployed app, see [License your app](https://developers.arcgis.com/android/license-and-deployment).
```suggestion
For information about licensing your deployed app, see [License your app](https://developers.arcgis.com/android/license-and-deployment/).
```

2021-02-24 21:43 UTC, merged