Added ViewBinding support, refractored some files and updated dependencies
Esri/nearby-android pull request #98
Opened 2020-10-20 10:15 UTC by MadRatSRP

2020-10-22 22:32 UTC, esreli commented
Thank you for your contribution @MadRatSRP. When some time frees up, our team will review your PR; this should be fairly soon. Thanks!

2020-10-24 15:37 UTC, MadRatSRP commented
No problem, have a nice day :)

2020-11-03 22:05 UTC, puneet-pdx requested changes
@MadRatSRP Thank you for your contribution. 

Overall PR looks good. I have left some comments regarding some reformatting and refactoring. 
Also since this PR cannot be directly merged into the `main` branch. I have created a separate branch off of `main` in which we can push changes from your fork and can later merge that branch into `main` .

2020-11-03 22:08 UTC, puneet-pdx commented on nearby-app/src/main/java/com/esri/arcgisruntime/opensourceapps/nearbyplaces/places/PlacesActivity.java
> +  /*
add missing *

```
/**
   * Prompt user to turn on location tracking and wireless if needed
   */
```

2020-11-23 17:32 UTC, puneet-pdx commented
@MadRatSRP do you think you will have some time to address these comments soon ?

2020-11-23 20:43 UTC, MadRatSRP commented
> @MadRatSRP do you think you will have some time to address these comments soon ?

Maybe on the next week

2020-12-11 19:24 UTC, puneet-pdx commented
Changes merged to `main` https://github.com/Esri/nearby-android/pull/101
Closing this PR

2020-12-11 19:24 UTC, closed without merging